# Generated by Django 3.1.4 on 2021-01-04 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='list',
            name='modified_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
